### ISSUE TITLE
Mauvais usage du champ nb_mandats

### ISSUE THREAD

**Issue by RouxRC** [jmtrivial/le-pigeon-nelson#10]
Hello,

Rigolo de découvrir cette réutilisation bien atypique par rapport à d'autres ! Nous l'ajouterons à notre liste ici : https://github.com/regardscitoyens/nosdeputes.fr/blob/master/doc/api.md#exemples-de-r%C3%A9utilisations-bas%C3%A9es-sur-lapi

Je me suis permis de jeter un oeil rapide au code et je note une petite erreur d'appréciation ici : 
https://github.com/Le-Pigeon-Nelson/le-pigeon-nelson/blob/eceaa497507ba8f94c9c5c7cc0be0a66cadefdfd/servers/deputes.php#L128

Le champ `nb_mandats` indique le nombre de mandat en cours, pas le nombre de mandats de députés remplis contrairement à ce que la phrase peut laisser entendre. Pour mesurer ce nombre, vous pouvez partir du champ `anciens_mandats` et compter les éléments (à raison d'un seul par période de 5 ans car un député peut par exemple être nommé ministre, laisser sa place à son suppléant, puis reprendre son mandat et donc comptabiliser 2 mandats au sein d'une même législature).

**Comment by jmtrivial** [comment]
Un gros merci pour ce retour et le regard attentif au code, je corrigerai ça très vite ! :-)

**Comment by jmtrivial** [comment]
J'ai modifié la phrase en indiquant le nombre d'autres mandats en cours, en respectant l'interprétation correcte du champ:

https://github.com/Le-Pigeon-Nelson/le-pigeon-nelson/blob/b98b592f028d19ef2074565736ba1788f153aa1a/servers/deputes.php#L133
